# Index
- key: "/"
  routes:
      - action: "App\\Main\\Presentation\\Controllers\\IndexController"
        method: "index"
        params: ""

# Empty
- key: "<@any>"
  routes:
      - action: "App\\Main\\Presentation\\Controllers\\IndexController"
        method: "emptyAction"
        params: ""
